### ISSUE TITLE
'Open video player'

### ISSUE THREAD

**Issue by DutchPete** [juliang22/ObsidianTimestampNotes#5]
If you highlight the URL the browser is the app that is in focus. As soon as you move your cursor to the Obsidian note, the URL highlight disappears.

If you then use the 'Open video player' hotkey I get a sticky note with the URL shown.

I am on MacOS.

**Comment by juliang22** [comment]
You have to paste in the url into obsidian, highlight it, then press the hotkey. Thanks for checking out the plugin!
