### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by stefansmr** [juliang22/ObsidianTimestampNotes#51]
Hi! I really do appreciate this plugin and am hoping to use it for my own work. My main concern is whether this plugin is still being maintained? I see the last release is currently around 1.5 years ago and the most recently closed issues/pull requests from July 2022. I do empathize with maintaining a free product and so totally understand if the time/effort bandwidth isn't there, I'd just prefer to have clear understanding! I appreciate your time and help.

**Comment by mattcoleanderson** [comment]
@stefansmr Yes! Going forward I will be helping @juliang22 maintain the project. So absolutely feel free to use the plugin and submit any issues you may come across.
