### ISSUE TITLE
Add more video players

### ISSUE THREAD

**Issue by DutchPete** [juliang22/ObsidianTimestampNotes#6]
Such as Bitchute, Rumble, Odysee, ……

**Comment by juliang22** [comment]
Right now I'm using the react player plugin for the video playing functionality and I don't currently plan on integrating other player types. I ~might~ build out support for local videos later on, but that a hard maybe. Thanks for checking out the plugin!

**Comment by DutchPete** [comment]
OK, until then I will not be able to use the plug-in. It is similar in functionality to the Media Extended plug-in, which I cannot use either for the exact same reason.
Too bad, I'll have to carry on using the conventional manual method.
